### ISSUE TITLE
Show console doesn't open a window

### ISSUE THREAD

**Issue by ClaudiaFrank** [dail8859/LuaScript#1]
Notepad++ v6.8.8
Build time : Dec 10 2015 - 01:11:37
Path : D:\Tests\npp\688\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (x64)
Plugins : LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by dail8859** [comment]
Darn I thought I had that fixed. Unfortunately the Notepad++ API documentation isn't the clearest. If possible, can you try out this new DLL to see if it fixes this issue? Thanks

[LuaScript.zip](https://github.com/dail8859/LuaScript/files/118542/LuaScript.zip)

**Comment by ClaudiaFrank** [comment]
Yes, both issues have been fixed - may I ask for an enhancement?
When script has been run, focus is passed to console, can editor get the focus instead?
Console is using folding margin (input and output), is this intended? This [looks](http://imgur.com/sWAy3uC) weird when using themes like bespin.

**Comment by ClaudiaFrank** [comment]
I shoudl have said
When script has been erroneously run, focus is passed to console, can editor get the focus instead?

**Comment by dail8859** [comment]
Yeah that definitely looks weird. I never use any theme other than the default but obviously using a different theme causes it to behave differently.

This was just the initial release so there is still lots of room for improvement. Thanks for these suggestions!

**Comment by dail8859** [comment]
That picture is really weird, because it shouldn't be highlighting that first row in the console *at all* or showing most of the margins...I'll check into it more.
