### ISSUE TITLE
Startup script doesnt run on start when path has non ANSI characters

### ISSUE THREAD

**Issue by OwnageIsMagic** [dail8859/LuaScript#10]
I guess it happens if path contains non ANSI symbols.
When I move NPP folder to `D:\Source` from `D:\Users\Владимир\Downloads\ `it starts working properly.

**Comment by dail8859** [comment]
I had kind of wondered about this for a while and hoped it just kind of automagically worked on its own...I guess not. I'll check into it.

**Comment by OwnageIsMagic** [comment]
Could you also build new alfa version with autocomplete, please

**Comment by dail8859** [comment]
Sure. I should be able to sometime this evening.

**Comment by dail8859** [comment]
You can download it below. Just unzip it and copy the DLL over the current one. For reference this is built from commit e269246

[LuaScript.zip](https://github.com/dail8859/LuaScript/files/159554/LuaScript.zip)

**Comment by OwnageIsMagic** [comment]
Its useles by now because I cant select anything from dropdown and disapperas after the first letter.
I hope it will be improved some day
any way its better than nothing:D thx

**Comment by dail8859** [comment]
Well obviously that isn't suppose to happen...so instead of being "useless" its called a bug. Plus you wanted alpha release...which means things might not work as expected. It's been working fine for me.

**Comment by dail8859** [comment]
If you can, could you try out this new DLL which should fix your issue with the file path. I want to make sure it works on your system before closing.

[LuaScript.zip](https://github.com/dail8859/LuaScript/files/159626/LuaScript.zip)


Also, if you are having an issue with the auto-completion please open a new issue because it should be working.

**Comment by Yaron10** [comment]
Hello dail,

I'm watching this repo.
You've been doing a great job. :+1: 

Thank you.

**Comment by OwnageIsMagic** [comment]
Error in console:
```
File:1: unexpected symbol near '<\239>'
Error occurred while loading startup script
```

**Comment by dail8859** [comment]
Out of curiosity, what encoding is your startup script using?

**Comment by OwnageIsMagic** [comment]
UTF-8 with BOM

**Comment by OwnageIsMagic** [comment]
Sorry converted another file
now it works perfectly
Seems like it doesn`t recognize BOM mark
