### ISSUE TITLE
能不能出一个能够格式化Lua代码的脚本

### ISSUE THREAD

**Issue by JmXtl3** [dail8859/LuaScript#100]
如果能出个可以快捷键格式化Lua语言的脚本，那就太好了

**Comment by dail8859** [comment]
The plugin is meant to provide an API into Notepad++ to control it, rather than trying to add functionality of an IDE. This is a bit outside the scope of this plugin.

**Comment by JmXtl3** [comment]
那么有没有希望出个可以自选版本的呢，有些时候代码里面会用到老版本的库函数名
