### ISSUE TITLE
Binding "insert" key

### ISSUE THREAD

**Issue by preuss** [dail8859/LuaScript#105]
I would like to have the insert key binding.

And I have looked in the code and you have commented this out:
//else if (_stricmp(cur, "insert") == 0) sk->_key = VK_INSERT;

I would like to do this:
npp.AddShortcut("Paste with Insert", "Shift+insert", function()
    editor:Paste()
end)

Is there another way to catch the insert key ?

**Comment by dail8859** [comment]
When I set up the mapping of shortcut keys, it appeared that there were keys that were not able to be mapped, including the insert key.

https://github.com/dail8859/LuaScript/blob/a4dd230779d099f16962bc4c00f465a7d58e36d9/src/SciTE/LuaExtension.cpp#L533-L541

I'm not sure if this is a Windows limitation or something within Notepad++ that prevented it. So unfortunately I don't know of any way to fix this.
