### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by OwnageIsMagic** [dail8859/LuaScript#11]
97273eed54a5382a1f3ffad7e6fb7aad2aa5fddf doesnt shows any icon
![aaa](https://cloud.githubusercontent.com/assets/10534634/13542929/adbecf28-e277-11e5-9676-250a73369b04.JPG)
![s](https://cloud.githubusercontent.com/assets/10534634/13542933/b123f724-e277-11e5-844c-7a0836a14d54.JPG)

**Comment by dail8859** [comment]
That icon is what Notepad++ uses when multiple dialogs are docked (for example having the function list open as well):

![capture](https://cloud.githubusercontent.com/assets/3694843/13543310/043226e2-e238-11e5-9c4a-2d6c4eefe2db.PNG)

And that's what 97273ee was for. That's the only place the icon shows up at.

**Comment by OwnageIsMagic** [comment]
Okay, my bad.
