### ISSUE TITLE
error() crashes Notepad violently with data loss

### ISSUE THREAD

**Issue by OwnageIsMagic** [dail8859/LuaScript#16]
![default](https://cloud.githubusercontent.com/assets/10534634/13547904/c3668038-e2f3-11e5-8359-1adbbad13a57.JPG)

**Comment by dail8859** [comment]
Is this a debug build of N++?

**Comment by OwnageIsMagic** [comment]
No, latest version from official site
```
Notepad++ v6.9
Build time : Feb 21 2016 - 21:27:55
Path : F:\Users\Владимир\Desktop\npp.6.9.binDELETEME\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10

```

**Comment by dail8859** [comment]
Maybe it's a Windows 10 thing or just random that yours crashes so violently.  Mine crashes more gracefully but at least I've found the problem.

**Comment by OwnageIsMagic** [comment]
It somehow relates to #15 because it produce this thousands of errors only when plugins enabled that crashes on `os.exit()`.

**Comment by dail8859** [comment]
Normally N++ allows each plugin to perform it's own cleanup when shutting down. However this bug (and also calling `os.exit()`) are killing off the main process and which could easily put N++ or other plugins into an unknown state which could generate a variety of different problems.
