### ISSUE TITLE
Make console inputbox resizeable

### ISSUE THREAD

**Issue by OwnageIsMagic** [dail8859/LuaScript#17]
(vertically)

**Comment by dail8859** [comment]
As much as I'd like to be able to have the input box resizeable, it adds more complexity and could cause confusion. For example:

- If the input is 1 line high:
  - `up` and `down` scroll through the history
  - `enter` runs the code
- If the input is larger than 1 line high:
  - `up` and `down` move the cursor
  - `enter` adds a new line
  - something like `ctrl+enter` could be used to run the code

I'm certainly open to more ideas and may try this out anyways but most likely this will feel "unnatural".

**Comment by OwnageIsMagic** [comment]
Open dev tools in browser (`F12`) there is nice example of how it should be implemented.
`Shift+Enter` Adds new line
`Enter` Sends input
`Up` and `Down` Move the cursor until end then move through history

**Comment by dail8859** [comment]
Ok thanks. I'll check that out.

**Comment by dail8859** [comment]
Ah! Yeah I really like that. I'll see what I can do.
