### ISSUE TITLE
Run current file behaves strange

### ISSUE THREAD

**Issue by ClaudiaFrank** [dail8859/LuaScript#2]
The following code is in the current file
`editor:AppendText("THIS")`
Press run current file results in 
`editor:AppendText("THIS")THIS`
Press save and again run current file - nothing happens, I guess because it's an invalid lua script.
Ok let's cleanup. Delete THIS at the end to get
`editor:AppendText("THIS")`
again, save it and press run cur..., still nothing happens. Just for fun, press again run... ->worked ??

**Comment by dail8859** [comment]
I've updated the download on the [Release](https://github.com/dail8859/LuaScript/releases) page and both this issue and the other you reported should be fixed. Thanks for reporting these!
