### ISSUE TITLE
Ability to load DLL libraries 

### ISSUE THREAD

**Issue by dail8859** [dail8859/LuaScript#22]
Investigate problem with loading external DLLs. 

CC @ClaudiaFrank

**Comment by ClaudiaFrank** [comment]
It seems lua is as restictive as python when it comes to compiled libraries.
Version of interpreter and lua main dll and 3rd party library needs to match. 
Try to compile socket library with lua 5.3.2

**Comment by dail8859** [comment]
Thanks! That is very useful information to know.

**Comment by ClaudiaFrank** [comment]
Can confirm, after build luasocket with lua5.3.2 I was able to create a tcp server.
Npp didn't crash anymore.
One thing is that lua5.3.2 dll needs to be placed somewhere it can be found - for testing I
used npp install directory.

**Comment by dail8859** [comment]
Awesome! Thanks for the info. Could you provide me with that new Lua socket library you compiled? (You'll have to zip it in order to upload it here.) I'm wanting to try testing a few things.

**Comment by ClaudiaFrank** [comment]
Tried to attach it but I always get the error

Something went really wrong, and we can’t process that file. 

Will send it to you directly.

I created a lua directory under plugins\config

and modified startup.lua with the lines
package.cpath = package.cpath .. ";.\\plugins\\Config\\lua\\?.dll"
package.path = package.path .. ";.\\plugins\\Config\\lua\\?.lua"

and lua5.3.2.dll has been copied to npp install directory.

Used a sample from the author of luasocket to test.
Be warned, the sample locks npp because it uses while 1 do ...... but for testing it is ok ;-)

-- load namespace
local socket = require("socket")
-- create a TCP socket and bind it to the local host, at any port
local server = assert(socket.bind("*", 0))
-- find out which port the OS chose for us
local ip, port = server:getsockname()
-- print a message informing what's up
print("Please telnet to localhost on port " .. port)
print("After connecting, you have 10s to enter a line to be echoed")
-- loop forever waiting for clients
while 1 do
  -- wait for a connection from any client
  local client = server:accept()
  -- make sure we don't block waiting for this client's line
  client:settimeout(10)
  -- receive the line
  local line, err = client:receive()
  -- if there was no error, send it back to the client
  if not err then client:send(line .. "\n") end
  -- done with client, close the object
  client:close()
end

**Comment by ClaudiaFrank** [comment]
as promised the zip - when unzipping it it will create

socket.lua -> file
socket -> directory
socket/core.dll -> file

Cheers
Claudia

**Comment by ClaudiaFrank** [comment]
I can't see an attachment, can you?

**Comment by dail8859** [comment]
Nope I don't see it.

**Comment by ClaudiaFrank** [comment]
[lua.zip](https://github.com/dail8859/LuaScript/files/160696/lua.zip)

**Comment by ClaudiaFrank** [comment]
Did you change something, this wasn't working before

**Comment by dail8859** [comment]
Never changed anything, but at least it is there now. I really appreciate it!!

**Comment by dail8859** [comment]
I was able to get this working with the files you provided. One question I had was the dependency on `lua5.3.2.dll`. I understand why it needs the DLL. I'm curious why it was looking for that exact name. Is that just how the socket library works? Or was that something you specified when building the new library?

**Comment by ClaudiaFrank** [comment]
It was need need to link against a library so I choose the lua5.3.2.lib. I guess that is where it is coming from.
The compile options were
/GS 
/analyze- 
/W3 
/Zc:wchar_t 
/I"..\build\vc12\include\lua\5.3.2\" 
/ZI 
/Gm 
/Od 
/Fd"Debug\core110.pdb" 
/fp:precise 
/D "WIN32" 
/D "_DEBUG" 
/D "_WINDOWS" 
/D "_USRDLL" 
/D "LUASOCKET_API=__declspec(dllexport)" 
/D "_CRT_SECURE_NO_WARNINGS" 
/D "LUASOCKET_DEBUG" 
/D "_VC80_UPGRADE=0x0710" 
/D "_WINDLL" /D "_MBCS" 
/errorReport:prompt 
/WX- 
/Zc:forScope 
/RTC1 
/Gd 
/Oy- 
/MDd 
/Fa"Debug\" 
/EHsc 
/nologo 
/Fo"Debug\" 
/Fp"Debug\core.pch"

The linker options
/OUT:"..\build\vc12\bin\lua\5.3.2\Debug\socket\core.dll" 
/MANIFEST 
/PDB:"..\build\vc12\bin\lua\5.3.2\Debug\socket\mime.pdb" 
/DYNAMICBASE:NO "lua5.3.2.lib" "ws2_32.lib" "kernel32.lib" "user32.lib" "gdi32.lib" 
                "winspool.lib" "comdlg32.lib" "advapi32.lib" "shell32.lib" "ole32.lib" 
                "oleaut32.lib" "uuid.lib" "odbc32.lib" "odbccp32.lib" 
/IMPLIB:"..\build\vc12\bin\lua\5.3.2\Debug\socket\core.lib" 
/DEBUG 
/DLL 
/MACHINE:X86 
/SAFESEH:NO 
/INCREMENTAL 
/PGD:"..\build\vc12\bin\lua\5.3.2\Debug\socket\core.pgd" 
/SUBSYSTEM:WINDOWS 
/MANIFESTUAC:"level='asInvoker' uiAccess='false'" 
/ManifestFile:"Debug\core.dll.intermediate.manifest" 
/ERRORREPORT:PROMPT 
/NOLOGO 
/LIBPATH:"..\build\vc12\bin\lua\5.3.2\Debug" 
/TLBID:1 

Maybe I did something wrong, I'm just starting cpp programming. Should I zip the .sln ?

**Comment by dail8859** [comment]
Thanks for the info.

> Should I zip the .sln ?

No that's fine I just didn't know if the name of the DLL was arbitrary or not.

**Comment by dail8859** [comment]
Note to self: https://github.com/diegonehab/luasocket/issues/106#issuecomment-60537751

> On Windows you can't use a static Lua library if you want to dynamically load C extension modules. You have to build the Lua library as a DLL, and link both lua.exe and your C extension modules to that DLL. The Makefile distributed with Lua has a mingw target for that (i.e. building the DLL and linking lua.exe).

**Comment by mjfs** [comment]
I also bumped into the issue of not being able to load DLL when trying to use [IUP](http://webserver2.tecgraf.puc-rio.br/iup/) library. No matter which version I choose, the same error message is shown. This also includes the version of Lua 5.3.4 + VC14 compiled IUP libs, corresponding to LuaScript release 0.8. I would really welcome any pointers on how to make this work, IUP seems like a perfect fit for GUI data input within NPP Lua script.

Minimum example and error message:

```lua	
package.cpath = package.cpath .. ";C:\\npp\\plugins\\LuaScript\\?.dll"
require("iup")
-- error loading module 'iup' from file 'C:\npp\plugins\LuaScript\iup.dll':
--     The specified procedure could not be found.
```

**Comment by dail8859** [comment]
AFAIK to make this work with arbitrary libraries, the stand-alone Lua DLL would have to be built, placed next to the Notepad++ exe, and then the "plugin part" to make it work with Notepad++ would use the Lua DLL. This would also mean all of the Lua API would also be exposed in the DLL which is what other libraries would need.

This would be quite a bit different from what is currently done. Plus it would then require admin privileges (in most cases) since Notepad++ is installed under `Program Files`. Also, this would not work with the current "Plugin Admin" since it is not able to copy exes into Notepad++'s root directory.

Your one option would be to build this plugin and also build the source code of IUP into the plugin as well. That's what I did to include the luawinfile module...which luckily wasn't hard to incorporate. See: https://github.com/dail8859/LuaScript/commit/04957d5814a8e17bac74ba931965f2fa44e06710

**Comment by xylographe** [comment]
Not a clue what is going wrong,
```
package.cpath = [[C:\ProgramData\lua\bin\lua\5.3\Release\?.dll]]; print(package.cpath)
C:\ProgramData\lua\bin\lua\5.3\Release\?.dll
package.path = [[C:\ProgramData\lua\bin\lua\5.3\Release\lua\?.lua]]; print(package.path)
C:\ProgramData\lua\bin\lua\5.3\Release\lua\?.lua
socket = require("socket")
error loading module 'socket.core' from file 'C:\ProgramData\lua\bin\lua\5.3\Release\socket\core.dll':
    Kan opgegeven module niet vinden.
```
(eng: Cannot find specified module.)

Using win7sp1 + npp 7.7 (32bit) + luascript 0.9.0.49 (32bit) + luasocket [current master](https://github.com/diegonehab/luasocket/commit/733af884f1aa18ff469bf3c4d18810e815853211)

AFAICT all required files are present. What exactly is it that lua can't find?

**Comment by dail8859** [comment]
I think the root cause is the Lua modules cannot find any of the Lua C API. In normal scenarios there is a DLL file which exports all the needed API functions for the modules to use. With this plugin, Lua is statically linked into the DLL, thus is does not expose any of the functions for interacting with the Lua C API.

**Comment by xylographe** [comment]
Ah yes, of course, how could I miss that?! Thank you very much!
After linking against `Lua.lib` from LuaScript everything is fine. :smile:

**Comment by dail8859** [comment]
You are saying you linked in lua.lib into luasocket?

**Comment by xylographe** [comment]
Yes, I built LuaScript, copied `Lua.lib` to the 5.3.4 lua lib directory, and edited `Lua.props` in LuaSocket:
```
    <!-- <LUALIBNAME>lua$(LUAV.Replace('.', '')).lib</LUALIBNAME> -->
    <LUALIBNAME>Lua.lib</LUALIBNAME>
```
Then I built LuaSocket, and followed the Installation instructions:
```
<LDIR>/ltn12.lua
<LDIR>/socket.lua
<CDIR>/socket/core.dll
<LDIR>/socket/http.lua
<LDIR>/socket/tp.lua
<LDIR>/socket/ftp.lua
<LDIR>/socket/smtp.lua
<LDIR>/socket/url.lua
<LDIR>/mime.lua
<CDIR>/mime/core.dll```
```
Where `<CDIR> == package.cpath == <NPP>\plugins\LuaScript`,
and `<LDIR> == package.path == <CDIR>\lua`

**Comment by dail8859** [comment]
@xylographe Thanks for the detailed info!

Statically linking in the lib file is not ideal for users to have to do, unfortunately that is the easiest option that I am aware of currently.

@anyone Unless there are some ideas on how to not require Lua to be linked into external DLLs, I will probably just end up closing this issue as `wontfix`

**Comment by ClaudiaFrank** [comment]
Hi dail,
is [this](http://lua-users.org/lists/lua-l/2013-11/msg00831.html) and [that](http://lua-users.org/lists/lua-l/2013-11/msg00831.html) something you might consider as way to go?

**Comment by xylographe** [comment]
First off, I don't mind the current situation.

Nonetheless, perhaps, the easiest and most user-friendly solution might be using a **standardized** lua DLL from [Lua Binaries](http://luabinaries.sourceforge.net/).

[quote on] _The LuaBinaries files are intended for advanced users and programmers who want to incorporate Lua in their applications or distributions and would like to keep compatibility with LuaBinaries, so they also will be compatible with many other modules available on the Internet._ [quote off]

There's plenty of choice, see for example [lua 5.3.5 dynamic libs](https://sourceforge.net/projects/luabinaries/files/5.3.5/Windows%20Libraries/Dynamic/).

Obviously, that means distributing two DLLs (`LuaScript.dll` and `Lua53.dll`), but with the new NPP plugin directory layout (each plug-in in a separate dir), that won't be a problem.

**Comment by dail8859** [comment]
> most user-friendly solution might be using a standardized lua DLL

Yes, I agree. I tried this a long time ago but it never worked the way I hoped (and it is possible I was doing something wrong). I haven't tried it since then but may give it one more attempt.

> that means distributing two DLLs

I am perfectly fine with that if it means the ability to load external libraries :)

> with the new NPP plugin directory layout (each plug-in in a separate dir), that won't be a problem.

I think the root problem is that the `Lua53.dll` would have to be in the same directory as `notepad++.exe` (this is the way PythonScript works I believe). And the Plugin Admin does not support coping files into the root N++ install dir.

**Comment by xylographe** [comment]
> I think the root problem is that the Lua53.dll would have to be in the same directory as notepad++.exe

The Compare plugin ([LibGit2Helper](https://github.com/pnedev/compare-plugin/blob/71b62e5d6d6c4b3f145c0252c341c5baecbe5ad2/src/LibGit2/LibGit2Helper.cpp#L30) and [SqliteHelper](https://github.com/pnedev/compare-plugin/blob/71b62e5d6d6c4b3f145c0252c341c5baecbe5ad2/src/SQLite/SqliteHelper.cpp#L33)) comes with three DLLs:
```
Compare
    git2.dll
    sqlite3.dll
Compare.dll
```
Under Plugin Manager these were placed in `<NPP>\plugins`, hence the nowadays unnecessary `Compare` subdir.

**Comment by dail8859** [comment]
To use those DLLs they have to manually wrap all the exported functions they need:

https://github.com/pnedev/compare-plugin/blob/71b62e5d6d6c4b3f145c0252c341c5baecbe5ad2/src/LibGit2/LibGit2Helper.cpp#L30

https://github.com/pnedev/compare-plugin/blob/71b62e5d6d6c4b3f145c0252c341c5baecbe5ad2/src/SQLite/SqliteHelper.cpp#L33

I'm not sure this makes sense to do for Lua as the C API is quite large and would need to be globally exposed to the module. 


If interested, look into load-time vs runtime-dynamic linking

**Comment by xylographe** [comment]
> I'm not sure this makes sense to do for Lua as the C API is quite large…

Good point. I had not taken that in consideration.

**Comment by ClaudiaFrank** [comment]
> I think the root problem is that the Lua53.dll would have to be in the same directory as notepad++.exe (this is the way PythonScript works I believe). And the Plugin Admin does not support coping files into the root N++ install dir.

Yes, this is how PS works but [there would be a way](https://github.com/bruderstein/PythonScript/issues/109#issuecomment-492388177) if Don could be conviced to use [LoadLibraryEx](https://docs.microsoft.com/en-us/windows/desktop/api/libloaderapi/nf-libloaderapi-loadlibraryexw)

**Comment by dail8859** [comment]
@ClaudiaFrank 

> is this and that something you might consider as way to go?

The first link seems interesting...and is pretty much doing what I figured would need done which is create a wrapper/proxy around all the functions exported by the DLL.

I tried the 2nd link and managed to make it so the LuaScript.dll exports all of the Lua C API...but not sure that gains me anything in the end :)

> if Don could be conviced to use LoadLibraryEx

Wow, this is *exactly* what is needed! Has anyone tried to "convince" Don (i.e. issue, PR)? Or is the problem just that it doesn't support XP? 

Personally I don't see the point in N++ trying to support XP.

I wonder if Don would be willing to accept a PR utilizing LoadLibraryEx but with the caveat that some plugins won't load correctly. (Granted some plugins probably don't work already just because they don't support XP themselves so I don't think much is lost in the end).

**Comment by xylographe** [comment]
From past PRs (100% acceptance, IIRC) it would appear you (@dail8859 ) are the most likely one to ‘convince’ Don.

As for XP, if the search flags are available, use LoadLibraryEx, else do whatever is done now. Ultimately it will be the choice of the plug-in's author, to make use of the new feature, or favour supporting XP.

**Comment by ClaudiaFrank** [comment]
> Has anyone tried to "convince" Don (i.e. issue, PR)?

From what I see, no and I agree with @xylographe, you seem to have the best choice to convince him :-)

@xylographe - don't understand this. Npp needs to use LoadLibraryEx. A plugin can only react on the
version npp has at the moment of loading the dll. 
How can a plugin developer interfer with it?

**Comment by xylographe** [comment]
@ClaudiaFrank 
What I meant, is that plug-ins can still support XP by using run-time dynamic linking.
But, of course, most plug-ins come in a single DLL, they won't be affected at all.

**Comment by dail8859** [comment]
@xylographe 

> From past PRs (100% acceptance, IIRC)

Its pretty high but not quite 100%.

_Slightly off topic_: Honestly what I've found that helps alot is logically walk through *why* the PR needs accepted. The code changes itself (assuming they are correct) aren't as important and can always be modified. So many times users submit a PR and it is just "here are code changes for feature X" and it is hard to convince Don to accept the PR based purely on the diff. (I speak from experience accepting PRs myself in other projects).

@ClaudiaFrank 

> you seem to have the best chance to convince him :-)

When I find some time I'll try the code changes and test it out and send a PR.

**Comment by xylographe** [comment]
It's early days yet, but I couldn't resist. After removing the Lua project from the LuaScript solution, replacing `src\lua\src` with the contents of [lua-5.3.5_Win32_dll15_lib.zip](https://sourceforge.net/projects/luabinaries/files/5.3.5/Windows%20Libraries/Dynamic/), and adjusting the LuaScript project accordingly ([branch l535](https://github.com/xylographe/LuaScript/tree/l535)), I rebuilt LuaScript, and copied `{LuaScript,lua53}.dll` to `plugins\LuaScript`. Thereafter, I rebuilt LuaSocket, linked against the lua-5.3.5 stubs lib too.

So far it's all been  running smoothly. :smiley:

**Comment by dail8859** [comment]
@xylographe That is very impressive and glad to hear you made some progress!

I *thought* I had tried something very similar myself about a week ago. I had the solution build two separate DLLs (one for Lua, one for the plugin itself). When I copied them both to `plugins\LuaScript` Notepad++ would immediately show an error that the DLL could not be found. If I put the Lua DLL in the root installation directory of `notepad++.exe` then it would work fine. I'm no expert but I'm confused how it is finding the DLL (but hey if it is working maybe its good not to question why it works) :)

**Comment by xylographe** [comment]
Oops, I should have mentioned that I didn't (yet?) apply the necessary change to NPP. To keep it simple I added `<NPP>\plugins\LuaScript` to the PATH environment variable. At first only in PoSH, to experiment, and later on also in the registry.

**Comment by ClaudiaFrank** [comment]
I gave it a try and did what @xylographe did in addition I changed [this](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/MISC/PluginsManager/PluginsManager.cpp#L133) to

~~~
pi->_hLib = ::LoadLibraryEx(pluginFilePath, NULL, LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR | LOAD_LIBRARY_SEARCH_SYSTEM32);
~~~

monitored by process monitor resulted in

~~~
Notepad++.exe	D:\Repositories\_cf\Npp770PS1040\bin\plugins\LuaScript\lua53.dll		SUCCESS	FASTIO_NETWORK_QUERY_OPEN
Notepad++.exe	D:\Repositories\_cf\Npp770PS1040\bin\plugins\PythonScript\python27.dll	SUCCESS	FASTIO_NETWORK_QUERY_OPEN
~~~

But this revealed that the needed VCRuntime used by the Lua53.dll or Python27.dll needs to be installed.
So I guess this is something to keep an eye on.

**Comment by ClaudiaFrank** [comment]
![grafik](https://user-images.githubusercontent.com/16170444/59506467-93fd1f00-8ea8-11e9-8c80-567070d55081.png)

**Comment by dail8859** [comment]
> I added <NPP>\plugins\LuaScript to the PATH environment variable

Oh ok that makes alot more sense now. :)

> But this revealed that the needed VCRuntime used by the Lua53.dll or Python27.dll needs to be installed.

Had not considered that but that is very good information to have. I think if the Lua DLL was built (rather than downloaded) then it would ensure that it matches the same VCRuntime as the LuaScript plugin itself. Unless I am mistaken?

**Comment by ClaudiaFrank** [comment]
> I think if the Lua DLL was built (rather than downloaded) then it would ensure that it matches the same VCRuntime as the LuaScript plugin itself.

I guess so too.

**Comment by xylographe** [comment]
All VS  C++ DLLs are VCRuntime dependant. I think, the objective was to “be compatible with many other modules available on the Internet,” which would imply the use of a standardized `luaNN.dll`?

**Comment by dail8859** [comment]
At one time my goal was to possibly include a lua package manger like LuaRocks (Lua's version of pip I guess). That way if a plugin needed luasocket for example you could just navigate to the LuaScript plugin directory and run:

> luarocks install luasocket

And have your module. Not sure that will actually happen some day but it's a nice thought.

**Comment by xylographe** [comment]
In the LuaScript console:
```
> rocks = require 'luarocks'
> rocks.install('luasocket')
```
:smile:

**Comment by ClaudiaFrank** [comment]
Is there something in lua like sys.path in pythonscript?
Meaning, can I force to look in a special directory to find lua files?

**Comment by dail8859** [comment]
@ClaudiaFrank 

Yes. `package.path` can be used to look for lua source files. `package.cpath` is used to look for lua DLL modules (they are simply string variables).

You can read up on the documentation on how to add paths to search but a quick example would be:

```lua
package.path = "C:\\?.lua;" .. package.path
```

This prepends a search path to use for finding lua modules. If you run `require "mymodule"` it will look for `C:\mymodule.lua`

A nice way to see the search paths is run `require "noexistingmodule"` and when it errors it will print a nice list of all the different places it searched for and failed :)

**Comment by ClaudiaFrank** [comment]
> A nice way to see the search paths is run require "noexistingmodule" and when it errors it will print a nice list of all the different places it searched for and failed :)

yes - that's what I've encountered - many lines telling me that my module can't be found there :-D

**Comment by xylographe** [comment]
Installed VCRuntime can be checked in the registry,
```
Win_x64
  x86: HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\DevDiv\vc\Servicing\14.0\RuntimeMinimum
  x64: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\DevDiv\VC\Servicing\14.0\RuntimeMinimum
Win_x86
  x86: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\DevDiv\VC\Servicing\14.0\RuntimeMinimum

REG_SZ Version >= "14.10.25017" ==> VC++ 2017
```
Unfortunately, Plugin Admin does not support prerequisites or dependencies. Only workaround seems to be a separate installer like CS-script plug-in, but I wouldn't recommend it.

**Comment by ClaudiaFrank** [comment]
I, personally, would deliver the dll which was built with the same runtime linked to it as the luascript dll is going to be linked to. 
Or, as dail said, build the dll together with the luascript plugin

**Comment by xylographe** [comment]
But, is not the whole point of having **shared** libraries to actually share?

**Comment by ClaudiaFrank** [comment]
What do you mean?
By providing a dll like you pointed out earlier others could load other shared lua librarys as long as
those are linked to the same vcruntime. That is my understand how those would work.
Did I particapte on a discussion with the wrong assumption? :-D

**Comment by xylographe** [comment]
Correct, if LuaScript would be the only assembly to support lua. But, if you want to use the stand-alone lua interpreter, or other lua supporting software, you will most likely be confronted with binary incompatibilities, forcing you to rebuilt lua dll and module dll(s) for each ‘participant’. That's where [LuaBinaries](http://luabinaries.sourceforge.net/) tries to offer a solution.

**Comment by ClaudiaFrank** [comment]
Either we are talking about the same but slightly offset or we are talking about different things.

If you want to have the possibility to load different dlls ignoring which vcruntime those are linked to
you need to ensure not to link LuaScript against a vcruntime but against msvcrt.dll.
But now you have the problem, that a 3rd party dll might request a vcruntime which isn't installed on the system. 
And from LuaScripts point of view it needs to provide a dll beforehand in order to be able to operate without being forced to install a local lua interpreter, therefore it needs to decide on a version anyway.

What do I miss?

**Comment by xylographe** [comment]
Imagine a second LuaScript to control, say, SubtitleEdit. For example,
```
local sub = subedit.enum("~\st\*.ssa")
while sub ~= nil do
  if sub.HI then sub.removeHI() end
  sub.fce()
  if sub.lang == "de" then sub.mrepl("common, german")
  sub.save("SubRip")
  sub = subedit.next()
end
```
Completely different interface, yet LuaScript for NPP and LuaScript for SE have one thing in common, they both use the lua interpreter. Hence, I would like them to use (_share_) the same `lua53.dll`. Then, when I build LuaSocket, LuaSec, or any other lua module with a C component, I only need one `socket.dll` , one `mime.dll`, etc.

Hence, no different DLL files, linked to different VCRuntimes. Only one set of DLLs shared between LuaScript for NPP, LuaScript for SE, and (also imaginary :) ) LuaScript for FileZilla.

**Comment by xylographe** [comment]
@ClaudiaFrank 

I rebuilt NPP with `LoadLibraryEx`. Needed to change v140_xp to v140 (undeclared LOAD_* flags).
Is that really necessary? If so, would Don be OK with it?

**Comment by ClaudiaFrank** [comment]
@xylographe - so we were talking about the same but didn't understand what each one of use was saying. Yes, that is what should be possible to do - one luaXX.dll which can be used, assuming it can be found, by each project. This dll so has a dependency which needs to be respected by its "to build/to use"
components. Means, if you build a component then this component has a dependency to this exact version of luaXX.dll - means also, if you install a lua component (already built) it must meet this criteria
as well.

Yes, xp needs to be dropped and Don already did this one or two times before someone else found
a way to reintroduce xp dependency.

**Comment by dail8859** [comment]
So to sum everything up, it looks like this is the path forward:
1. Convince Don to accept a PR introducing `LoadLibraryEx` (This is not only benenficial to this plugin but potentially any others that have DLLs they need to load)
1. Split this project up and create 2 DLL files (`luaXX.dll` and `LuaScript.dll`)
1. Distribute header files and `lib` for the `luaXX.dll` library.
1. Anyone else wanting to add an external Lua module to LuaScript would use the `lib` and header files to link against.

**Comment by xylographe** [comment]
@ClaudiaFrank 

> …one luaXX.dll which can be used, assuming it can be found…

There is a standard lua directory structure, but under Windows the most convenient way (IME) is to link `lua53.dll` to the install dir (i.e. `<NPP>\plugins\LuaScript`).

> This dll so has a dependency which needs to be respected by…

LuaRocks analyses the PE, and uses the same runtime to build the ‘rock’. As for proprietary software, under Windows this is always deployed as a self-contained installation, so no hopes there. :(

I was wondering, if there is a particular reason, why you chose,
`LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR | LOAD_LIBRARY_SEARCH_SYSTEM32`, and not
`LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR | LOAD_LIBRARY_SEARCH_DEFAULT_DIRS`.
I believe, the former will _not_ perform a PATH search?

@dail8859 
I was thinking, if the transition from `v140_xp` to `v140` is unwanted, than, perhaps, the ‘ugly’ way,
```
#ifndef	LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR
#define	LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR	0x00000100
#endif
// etc.
```

**Comment by dail8859** [comment]
> I was thinking, if the transition from v140_xp to v140 is unwanted, than, perhaps, the ‘ugly’ way,

Yes I was thinking the same thing as well. This would still allow Notepad++ to be compatible with XP, even if some of the plugins are not.

**Comment by ClaudiaFrank** [comment]
Sorry for answering so late, but, luckily, I was on vacation :-)
@dail8859 - sounds like a reasonable approach to me.
@xylographe - no, there was not really a reason why I chose this one over one of the others. Just used it to test that oring works.

**Comment by dail8859** [comment]
So now that both Notepad++ and LuaScript support this...what's next?

My initial thought is to distribute some sort of "LuaScript SDK" which would include some of the Lua header files and also the lua.lib file so that others can use those to compile their own code.

If someone wanted to use a Lua package manager (something like luarocks) then that might be quite a bit tougher and I don't have enough experience with those to know what is/isn't possible.

**Comment by xylographe** [comment]
I think, you need to include the stubs library and the header files,
```
 \plugins\LuaScript\lua53\include\lauxlib.h
 \plugins\LuaScript\lua53\include\lua.h
 \plugins\LuaScript\lua53\include\lua.hpp
 \plugins\LuaScript\lua53\include\luaconf.h
 \plugins\LuaScript\lua53\include\lualib.h
 \plugins\LuaScript\lua53\lib\Lua.lib
```
LuaRocks users can use your `Lua.lib`/`Lua.dll` pair (for example by creating symlinks in the right location), or they can rebuild `LuaScript.dll`  with a standard lib pair from LuaBinaries. I think, you may assume these users know what they're doing, hence, you probably shouldn't waste your time on it.
