### ISSUE TITLE
Reset lua state without n++ restart

### ISSUE THREAD

**Issue by OwnageIsMagic** [dail8859/LuaScript#24]
There are many ways to mess wih global env. :D

**Comment by dail8859** [comment]
I wanted to do this in the past but unfortunately this probably won't ever be possible because some things can only run while Notepad++ is starting up e.g. adding shortcuts. Re-initializing the Lua state could lose the current shortcuts and new ones would not be able to be registered.

**Comment by OwnageIsMagic** [comment]
What about creating several instances 1 internal for shortcuts registering and serve other in multiple panes?

**Comment by dail8859** [comment]
It would still have the problem of not allowing shortcuts to be registered later. That is just one scenario and in the future there may be more. Is there a specific reason for wanting to reset the Lua state other than just clearing out unneeded functions/variables?

**Comment by OwnageIsMagic** [comment]
Something like
```
package = 0;
print = 0;
```
Will delete all references to print function

**Comment by dail8859** [comment]
If there was a case that the state *might* need reset on even a semi-regular basis I could see possible adding this feature in. 

> Will delete all references to `print` function

This is called user error. I see no problem making the user restart Notepad++ in this case ;) I'll close this for now but unless there would be a regular use case that someone might need to reset it then I don't think this will get implemented.
