### ISSUE TITLE
ClearConsole() should reset horizontal width

### ISSUE THREAD

**Issue by dail8859** [dail8859/LuaScript#25]

**Comment by OwnageIsMagic** [comment]
You mean remove horizontal scroll bar?

**Comment by dail8859** [comment]
Yes.

**Comment by dail8859** [comment]
Not permanently though. For example if this is ran.

```lua
print(string.rep("n", 500))
npp.ClearConsole()
```
Then there's no reason to have the scrollbar still there until it is needed again.

**Comment by OwnageIsMagic** [comment]
The title confused me.
At first I thought that you want to resize undocked console widget )

**Comment by OwnageIsMagic** [comment]
Also turn on line wrapping will be good idea

**Comment by dail8859** [comment]
> Also turn on line wrapping will be good idea

You can do this yourself with 

```
console.WrapMode = SC_WRAP_WORD
```

**Comment by OwnageIsMagic** [comment]
`console` userdata is still undocumented
It is just another scintilla window, am I right?

**Comment by dail8859** [comment]
> It is just another scintilla window, am I right?

Yes. Anything you can do with the `editor` you can do with the `console`. However, keep in mind that since the `console` is set as read-only some functionality may not work as expected (e.g. adding/removing text), unless you specifically run `console.ReadOnly = false` before each time you want to modify the text (which is one of the caveats I alluded to in #14).
