### ISSUE TITLE
Non of the precompiled plugins/libraries can be downloaded.

### ISSUE THREAD

**Issue by ClaudiaFrank** [dail8859/LuaScript#28]

**Comment by dail8859** [comment]
Works for me. Is it a github issue?

**Comment by ClaudiaFrank** [comment]
I have to apologize, it is working - firefox prevented to download because of cross site issue.
Source.zip is available at github whereas dll gets redirected to github-cloud.s3.amazonaws.com

**Comment by dail8859** [comment]
No problem. Glad it is working.
