### ISSUE TITLE
Pasting long text to console inputbox shows horizontal scrollbar

### ISSUE THREAD

**Issue by ClaudiaFrank** [dail8859/LuaScript#3]
When text is pasted to inputbox which is larger than visible width of input box you will get
a scrollbar which [overlays input box](http://imgur.com/a9XzWDJ).

**Comment by dail8859** [comment]
Thanks for the report! :)

**Comment by dail8859** [comment]
Also I have no idea why it is showing the margins or highlighting all of the output for you. Does it always do that?

**Comment by ClaudiaFrank** [comment]
Yes, I 've download a fresh minimalistic package, create plugins directory and copied luascript.dll into it.
Still [colouring](https://imgur.com/6bSclSB) but version line is now clear.

**Comment by dail8859** [comment]
It is still suppose to highlight it on likes that start with `>` but now it looks as it is suppose too! So weird what it was doing before.

Thanks for all your help!

**Comment by ClaudiaFrank** [comment]
When copying config.xml from old to new minimalistic it happens again.
Will try to investigate what is causing it.

**Comment by dail8859** [comment]
It is possible it might have something to do with the original problem you encountered with the console not showing up that put some bad value in the config.xml file. I think the only thing that gets saved in the config.xml file due to the plugin is under the `<GUIConfig name="DockingManager"...` tag which looks something like:

```
<PluginDlg pluginName="LuaScript.dll" id="-1" curr="1" prev="-1" isVisible="no" />
```

**Comment by ClaudiaFrank** [comment]
OK -> When having a default language (settings->preferences->new docmunet) set coloring
reappears and coloring is done depending on language selected.

**Comment by dail8859** [comment]
Oh! Thank you for finding that out!! I never would have guessed that is it. Since the input and output are Scintilla instances that are "created" for you by Notepad++ apparently it carries over the default options like that.
