### ISSUE TITLE
Docked console doesn't show name nicely.

### ISSUE THREAD

**Issue by ClaudiaFrank** [dail8859/LuaScript#4]
Just fancy stuff - nothing important.

When having lua script console and another window, like python script console, docked together
the tab doesn't show LuaScript nicely

changing the following in ConsoleDialog.cpp would solve it

m_data.pszName = TEXT("  LuaScript");

but not sure if this is the best way to do it.

**Comment by dail8859** [comment]
Yeah I agree it looks weird. I may do as you suggest and just add a space before it for now. I think by default Notepad++ always just assumes there is an icon registered with the docked dialog so I may check into that option as well.
