### ISSUE TITLE
Enable LuaScript specific keywords highlighting for startup.lua editor

### ISSUE THREAD

**Issue by OwnageIsMagic** [dail8859/LuaScript#40]
Highlight Sci constants

**Comment by OwnageIsMagic** [comment]
closed

**Comment by dail8859** [comment]
Any particular reason for closing? It's a good idea.

**Comment by OwnageIsMagic** [comment]
I thought you use custom lexer, but then i look into the code [LuaConsole.cpp#L200-L201](https://github.com/dail8859/LuaScript/blob/master/src/LuaConsole.cpp#L200-L201)
I will rename it and reopen

**Comment by OwnageIsMagic** [comment]
And how this reflection magic happens in cpp?

**Comment by dail8859** [comment]
All of the constants/properties/functions are stored in an "interface table" (e.g. [this one](https://github.com/dail8859/LuaScript/blob/c9b7dfe15a2cd3a51064236dc67b1a005b09ac95/src/SciIFaceTable.cpp) for Scintilla) which is used so Lua knows how to pass the data to Scintilla and Notepad++. 

I actually have this following chunk of code in my own startup script which does exactly what you proposed (note the string is really long so I snipped most of it out, and it is hard coded):

```lua
npp.AddEventHandler("OnSwitchFile", function(filename, bufferid)
	if npp.BufferLangType[bufferid] == L_LUA and npp:GetFileName() == "startup.lua" then
		editor.KeyWords[4] = "ANNOTATION_BOXED ANNOTATION_HIDDEN <snip> VISIBLE_SLOP VISIBLE_STRICT"
		editor.StyleFore[SCE_LUA_WORD5] = editor.StyleFore[SCE_LUA_PREPROCESSOR]
		editor.StyleBold[SCE_LUA_WORD5] = true
	end
end)
```

But having this type of functionality (and more dynamic for future changes) is probably worth putting into the actual plugin.

**Comment by OwnageIsMagic** [comment]
maybe also add `editor` `editor1` `editor2` `npp` `console`?

**Comment by dail8859** [comment]
Personally I wouldn't find it that beneficial and this can easily be added by the user. Also these values are unlikely to ever change, as opposed to the global constants which may get updated more often.  

Adding them to the auto-complete list isn't a bad idea though.

**Comment by OwnageIsMagic** [comment]
default lexer highlight std lib tables like 
![image](https://cloud.githubusercontent.com/assets/10534634/21362926/6a4ba1da-c6fb-11e6-8505-b4b71e5fb44c.png)

**Comment by dail8859** [comment]
I'm not really a fan of how it is done but I just copied it from Notepad++'s default style. So for consistency sake, I'm fine with its current behavior. I may tweak it a bit (e.g. remove the italic) but nothing major.

**Comment by OwnageIsMagic** [comment]
is there any way I can append them to `editor.KeyWords[3]` manually ?
there is no getter for keywords
seems like the only way is add them to new keyword group

**Comment by dail8859** [comment]
> seems like the only way is add them to new keyword group

Yeah I think this is the only way.

**Comment by OwnageIsMagic** [comment]
I tried this:
```lua
npp.AddEventHandler("OnSwitchFile", function(filename, bufferid)
	if npp.BufferLangType[bufferid] == L_LUA and npp:GetFileName() == "startup.lua" then
		editor.KeyWords[8] = "editor editor1 editor2 npp console"
		editor.StyleFore[SCE_LUA_WORD8] = 0xff0000
	end
end)
```
but nothing changes

**Comment by dail8859** [comment]
You need to use `editor.KeyWords[7]` since the KeyWords are indexed starting at 0.

**Comment by OwnageIsMagic** [comment]
Thanks
and one more question
I can't find sci message which assign style to keyword set

**Comment by dail8859** [comment]
The way you did it (which is the same way I posted above) is how it is done. You set the lexer's keyword list and then a style that the lexer uses for that keyword list.

**Comment by OwnageIsMagic** [comment]
for example
how can i assign my style `127` to `editor.KeyWords[8]`
There are 9 keyword groups (0-8)
but only 8 `SCE_LUA_WORD` - `SCE_LUA_WORD8` styles

**Comment by dail8859** [comment]
It is hard coded in each lexer what style it uses for each list. The current Lua lexer only uses 8 word lists. See [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/lexers/LexLua.cxx#L424-L434).
