### ISSUE TITLE
[Request] Don't clear input after execution

### ISSUE THREAD

**Issue by Yaron10** [dail8859/LuaScript#49]
Hello dail,

I often want to run the same command several times in a row (in the console).
Is there a reason you clear the input after the execution?
Could you please add an option not to clear it?

Thank you.
BR

**Comment by dail8859** [comment]
> Is there a reason you clear the input after the execution?

I guess because every other console and command line tool clears the input so its only natural to do the same here. You can press the up and down arrow to scroll through your recent history of commands.

**Comment by Yaron10** [comment]
Thank you dail. I didn't know you could use the up and down arrows.
