### ISSUE TITLE
How to use that plugin

### ISSUE THREAD

**Issue by sibojan** [dail8859/LuaScript#52]
Hi ,

I found this plugin very promising but the installation is not documented.

Would you provide  formal instruction of how to install that in the README.md.

I tried to simply put the LuaScript.dll in the plugin folder but got no success. 

Thank you,

**Comment by dail8859** [comment]
> I tried to simply put the LuaScript.dll in the plugin folder but got no success.

That is all you have to do. You can also install it from the Plugin Manager.

**Comment by sibojan** [comment]
I could not find that in the Plugin Manger using the name LuaScript. 
How can I test if it is in effect in the situation of putting the LuaScript.dll in the plugin folder ?

**Comment by dail8859** [comment]
> I could not find that in the Plugin Manger using the name LuaScript.

I can confirm it is there, not sure why it's not working for you.

> How can I test if it is in effect in the situation of putting the LuaScript.dll in the plugin folder ?

It will show up in the "Plugins" menu just like a normal plugin would.

**Comment by sibojan** [comment]
![snap21](https://cloud.githubusercontent.com/assets/11802171/21778757/b638d0dc-d672-11e6-9629-1f8f9e15ea6e.jpg)

This is all the plugins with head letter L  I found in the plugin manager.

**Comment by sibojan** [comment]
I installed it successfully by just putting it in plug in folder.

**Comment by dail8859** [comment]
![capture](https://cloud.githubusercontent.com/assets/3694843/21778880/2bb905e8-d673-11e6-9b99-6d912cf4f73d.PNG)

Are you sure it is not listed under the "Updates" or "Installed" tab?

**Comment by sibojan** [comment]
You are right.  It is in the installed tab.
Sorry for the confusions I caused.
