### ISSUE TITLE
[Question] Restore default selection color after calling editor:SetSelBack()

### ISSUE THREAD

**Issue by Yaron10** [dail8859/LuaScript#57]
Hello dail,

Thanks again for this great plugin.

May I request your help? - I'd appreciate it.

Using `editor:SetSelBack(true, 255, 0, 0)` sets the selection background color to red as expected.
How do I restore the *default color* (set in Style Configurator)?

Using `editor:SetSelBack(false, 255, 0, 0)` results in "no background color".
>If it is set to false, the default styled colouring is used and the fore or back argument has no effect.

(From http://www.scintilla.org/ScintillaDoc.html#SCI_SETSELBACK).

What am I missing here?

Best regards.

**Comment by dail8859** [comment]
Hi Yaron,

First I should state that [`SetSelBack()`](http://dail8859.github.io/LuaScript/classes/Editor.html#Editor:SetSelBack) only takes 2 parameters, the boolean flag and the color. Color values are single integers storing the bytes in BGR order. So your call to:

> editor:SetSelBack(true, 255, 0, 0)

Should actually be:

> editor:SetSelBack(true, 0x0000FF)

It had the side effect of still working as expected...however this is unrelated to your main question but figured I would point it in case it gives you trouble later :)

-----

You are correct that using `false` results in no background. As far as I know there is no Scintilla API to get this value before changing it...and Notepad++ doesn't expose any type of API either to get any type of styling information stored by the Style Configurator. 

So unfortunately I don't have any solution for you other than manually parsing Notepad++'s xml file and reading the value...which is definitely not an ideal solution.

**Comment by Yaron10** [comment]
Hello dail,

Thank you for the detailed and interesting explanation. I do appreciate it.

I used `editor.setSelBack(True, (255, 0, 0))` in an old Python Script.
Trying to convert it to Lua, this was my approach.
But, obviously, you're right: you get the wrong color when using *other* RGB values in Lua.

How do you explain the "If it is set to false, the default styled colouring is used and the fore or back argument has no effect." statement?
Is it correct in other Scintilla-based editors but not in NPP?

Best regards.

**Comment by dail8859** [comment]
> If it is set to false, the default styled colouring is used...

As far as I can tell this is correct. If you set the flag to `false` then the selection will just use whatever style the selected text has and not change the background at all.

>  and the fore or back argument has no effect.

This just means the 2nd parameter doesn't matter at all if the flag is `false`.

> Is it correct in other Scintilla-based editors but not in NPP?

I'm not sure.

**Comment by Yaron10** [comment]
Hello dail,



> and the fore or back argument has no effect.
> ...
> This just means the 2nd parameter doesn't matter at all if the flag is false.

Yes, this is the easy and well-phrased part. :)



> If it is set to false, the default styled colouring is used...
> ...
> As far as I can tell this is correct. If you set the flag to false then the selection will just use whatever style the selected text has and not change the background at all.

That's nice. I misinterpreted those words.

Thanks again for your kind help. Highly appreciated. 



Best regards.
