### ISSUE TITLE
Pythonscript like execution of scripts

### ISSUE THREAD

**Issue by Stretto** [dail8859/LuaScript#58]
I am new to luascript and rather use lua than python. One thing that is baffling to me is how to execute a script. We can execute the current "files" as a script but that doesn't let us  modify files like pythonscript AFAIK.

e.g., with pythonscript I can create a python file, then open the file I want to modify, and then go to pythonscripts menu and execute the script and it will modify the file.

I imagine the same types of things can be done with lua but it seems more inconvenient(probably have to use console?)

**Comment by dail8859** [comment]
Hi. I am aware some "getting started" documentation is lacking and #56 will start to help in this area a bit.

LuaScript works a bit different from PythonScript as it requires *functions* to be registered as opposed to individual *scripts*. This is done using [`AddShortcut`](http://dail8859.github.io/LuaScript/classes/Notepad.html#Notepad.AddShortcut). This will create a new menu item that can be manually clicked on or tied to a keyboard shortcut. 

On startup LuaScript runs the startup.lua file (`Plugins > LuaScript > Edit Startup Script`) and this is where you can register shortcuts. For example if you used this code in the startup script:

```lua
-- Mimic Visual Studio's "Ctrl+C" that copies the entire line if nothing is selected
npp.AddShortcut("Copy Allow Line", "Ctrl+C", function()
    editor:CopyAllowLine()
end)

-- Mimic Visual Studio's "Ctrl+X" that cuts the line if nothing is selected
npp.AddShortcut("Cut Allow Line", "Ctrl+X", function()
    if editor.SelectionEmpty then
        editor:CopyAllowLine()
        editor:LineDelete()
    else
        editor:Cut()
    end
end)
```

Then 2 new menu items would show up (i.e. "Copy Allow Line" and "Cut Allow Line"). Also you aren't required to provide a keyboard command, for example replacing `"Ctrl+X"` with `""` or `nil` is valid.

**Comment by moon6969** [comment]
I much prefer lua to python scripting, but struggling to get a good workflow developing npp lua plugins.

Biggest issue is having to open a new instance of npp to test each time I make a change - then move/resize to 2nd monitor and mess about to set appropriate test scenario. 

Contrast this to python script where you edit the script, tab to other npp and can test all changes against the same test npp instance.

Lesser issue is having to manually edit CustomizeToolbar.btn to add the test function to the toolbar since hotkeys not convenient for me.

Lua & Python are not my native language so I very much develop by trial & error - so I am finding it a little frustrating!

Am I missing some better method of testing changes to the npp lua scripts I write.

Cheers for all the effort on this plugin btw :)

**Comment by dail8859** [comment]
There are a few different ways you could do it I guess. Taking the example above what I would normally do is just create a function that does what I want. So I would write something like this in my file:

```lua
function myfunction()
    if editor.SelectionEmpty then
        editor:CopyAllowLine()
        editor:LineDelete()
    else
        editor:Cut()
    end
```

I either copy/paste/run this into the LuaScript console, or run `Plugins > LuaScript > Execute Current File` (you can also tie this to a shortcut via Notepad++'s shortcut mapper to make this easier). 

Switch to a test scenario file I want to test it on, then in the console run `myfunction()`. If it doesn't work  I switch back to the Lua file, edit it, run it, etc. Once complete I can wrap it in a `AddShortCut()` call if I want.

You could also have the script itself switch to the file to test by adding this to the top of `myfunction()`:

```lua
npp:SwitchToFile("my_test_scenario.txt")
```


--- 

I am certainly open to ideas and suggestions. I haven't used the PythonScript plugin for anything that involved so I never had a need to find a good workflow.

**Comment by moon6969** [comment]
Ah! The SwitchToFile thing might do the trick thanks.
