### ISSUE TITLE
Enhance links to SCI docs

### ISSUE THREAD

**Issue by moon6969** [dail8859/LuaScript#59]
The main LuaScript reference has links for most functions to SCI documentation for the matching function...
>   <strong>Editor.CurrentPos</strong>
> Sets the position of the caret.
>   <ul>
>     <li>
>     <span class="parameter">CurrentPos:</span> position</li>
>   </ul>
>   <h3>See also:</h3>
>   <div style="margin-left: 2em">
>     <a href="http://www.scintilla.org/ScintillaDoc.html#SCI_SETCURRENTPOS">SCI_SETCURRENTPOS</a>
>   </div>

However editor.CurrentPos also implements SCI_**G**ETCURRENTPOS, but my search of LuaScript docs for SCI_GETCURRENTPOS failed.

So I suggest all similar LuaScript functions that roll GET & SET into a "property" should include a "See also:" reference to both SCI functions. Also the description could also indicate "gets or sets..."!

Minor related question: Why do the LuaScript docs have captial E in Editor.CurrentPos etc. when the object is a lower case "editor"?
It did cause quite some headscratching when code copied directly from the docs didn't work in practice!

**Comment by dail8859** [comment]
The documentation is far from perfect. It is generated by parsing through the documentation that SciTE uses for its Lua API. See [this html file](https://github.com/dail8859/LuaScript/blob/master/docs_gen/PaneAPI.html). This saves having to manually create the documentation (which does not sound fun :) ), but as you have pointed out it has its flaws. 

There might be a better way by pulling info straight out of the [interface file](https://github.com/dail8859/LuaScript/blob/master/scripts/Scintilla.iface) that Scintilla provides, but even that would take a bit of work.

> Why do the LuaScript docs have captial E in Editor.CurrentPos etc. when the object is a lower case "editor"?

Although Lua doesn't fundamentally have classes, you can think of `Editor` as the class, and `editor` as the instantiation of that class. There are also other instantiations of `editor1`, `editor2`, and `console`.

**Comment by moon6969** [comment]
Understood - documentation is something I rapidly lose enthusiasm for maintaining after initial creation!

Perhaps a paragraph at the top of the [Editor page](https://dail8859.github.io/LuaScript/classes/Editor.html) about the get/set thing might save some headaches for newcomers going forward!

Something along the lines of...
Some Scintilla SCI_SETxxx and SCI_GETxxx functions are implemented in LuaScript as a single property.
EG: Editor.CurrentPos is a read/write property that calls both SCI_GETCURRENTPOS and SCI_SETCURRENTPOS... the automatically generated docs below may only refer to one or the other.

**Comment by dail8859** [comment]
I quickly loose interest as well :) And the documentation is generated using LDoc...which is fine for simple stuff but anything beyond that is quite painful :)

> Something along the lines of...

That's a good idea.
