### ISSUE TITLE
Run plugin menu command

### ISSUE THREAD

**Issue by moon6969** [dail8859/LuaScript#60]
How can I run a custom menu command?

[Notepad:MenuCommand](https://dail8859.github.io/LuaScript/classes/Notepad.html#Notepad:MenuCommand) only appears to accept the default npp commands with predefined [IDM_xxx](https://github.com/dail8859/LuaScript/blob/master/src/Npp/menuCmdID.h) constants.

I've had to write a PythonScript (using [notepad.runPluginCommand](http://npppythonscript.sourceforge.net/docs/latest/notepad.html#Notepad.runPluginCommand)) in order to script Plugins -> LuaScript -> Execute Current File :blush:

Use case: improve workflow when developing LuaScripts as discussed in issue #58...

During development of a new LuaScript I include [npp:SwitchToFile](https://dail8859.github.io/LuaScript/classes/Notepad.html#Notepad:SwitchToFile)(`"C:\\PathTo\\TestFile.txt"`) at the top.

I have setup npp plugin "[Customize Toolbar](https://sourceforge.net/projects/npp-customize/)" to give me a toolbar icon for "Plugins -> LuaScript -> Execute Current File"

So clicking the button while the dev LuaScript is active will automatically run it against my nominated test script.

All good so far, but generally I then switch to the TestFile.txt to examine the test results... clicking the button now will try to execute the test document rather than the dev LuaScript - this gets old very quickly (especially when the TestFile.txt is actually TestFile.lua!!)

So it would be good to have a _Lua_ script that:
- Remembers current active doc
- Activate dev LuaScript doc
- Execute Current File
- Activate the original active doc
- Bonus points for a method to avoid hardcoding the path to the dev LuaScript, but I can't figure out an elegant way to persist data between script calls (I asked about this on the PythonScript forum [here](https://sourceforge.net/p/npppythonscript/discussion/1188886/thread/376631a7/)).

Thanks.

**Comment by dail8859** [comment]
> How can I run a custom menu command?

Only calling menu commands using the IDM constants as you pointed out is currently possible. The API for Notepad++ is limited to this as well.

However, as you've seen with PythonScript it is possible. I've never looked at that part of the code but I'd guess it is using the Win32 API calls to get the menus of Notepad++ to find the appropriate one. In theory that code could be reused within LuaScript but have no idea how hard that would be (I don't really know enough about Win32 development to write an implementation from scratch).

---

> So it would be good to have a Lua script that...

If I am understanding correctly you mean something like this?

```lua
cur_file = npp:GetFullCurrentPath()
npp:SwitchToFile("C:\\PathTo\\DevFile.lua")

-- Note: currently there is no way to call the "Execute Current File" command, but we can work around it for now by having Lua execute the Lua code for us
-- This is pretty much what LuaScript does internally anyways :)
load(editor:GetText())()

npp:SwitchToFile(cur_file)
```

---

> I can't figure out an elegant way to persist data between script calls

Variables in Lua are global by default. So you can execute this script multiple times and it will always print the next value.

```lua
-- undefined variables are nil
if myvar == nil then
	myvar = 0 -- initialize it the first time
else
	myvar = myvar + 1 -- increment it
end
print(myvar)
```

So if you didn't want to hard code the `"C:\\PathTo\\DevFile.lua"` above. You could change that line to:

```lua
npp:SwitchToFile(dev_file)
```

And before you run that script you can use the LuaScript console to execute:

```lua
dev_file = "C:\\PathTo\\DevFile.lua"
```

Then you can always change `dev_file` from the console later.

**Comment by moon6969** [comment]
Thanks again Dail... l assumed that each script ran in it's own instance!

So together with load(editor:GetText())() tip I now have a fine arrangement to quickly bash out npp LuaScripts.
