### ISSUE TITLE
Crash on 64-bit

### ISSUE THREAD

**Issue by cmagnush** [dail8859/LuaScript#61]
Running the following in a 64-bit Notepad++ LuaScript console causes a crash:
`npp.BufferFormat[npp.CurrentBufferID]`

The problem seems to be in iface_function_helper() in LuaExtension.cpp. I made the following change on the 0.7.0 sources, to fix some incorrect casts:

```
@@ -1052,3 +1052,3 @@
                } else if (IFaceTypeIsNumeric(func.paramType[i])) {
-                       params[i] = static_cast<long>(luaL_checkinteger(L, arg++));
+                       params[i] = static_cast<sptr_t>(luaL_checkinteger(L, arg++));
                }
@@ -1123,3 +1123,3 @@
        } else if (IFaceTypeIsNumeric(func.returnType)) {
-               lua_pushinteger(L, static_cast<int>(result));
+               lua_pushinteger(L, static_cast<lua_Integer>(result));
                resultCount++;
```

This fixes the crash, and some scripts I've written still works.

**Comment by dail8859** [comment]
Thanks for opening the issue and providing a fix. When I get a bit of free time this next week I'll look into it more.

**Comment by dail8859** [comment]
I wasn't able to reproduce the crash myself but I know that it can be difficult to reproduce these types of overflow-related issues. However, these changes seem reasonable given the actual data types being used.

Thanks again for the report and fix! :)
