### ISSUE TITLE
How does one open a file into the second view i.e. 'editor2'?

### ISSUE THREAD

**Issue by charlesmallah** [dail8859/LuaScript#64]
This plugin seems really interesting and I am writing a few scripts to test it out.

I've managed to execute other applications for code linting and clean-up and I would like to load the output file into the second view so that it is side-by-side with the source.

Is there a command for this in LuaScript, to open view 2 and load a file into it?

**Comment by dail8859** [comment]
Glad you are finding it useful. What you can do is open the file then move it to the other view. This is the same as running the menu command `View > Move/Clone Current Document > Move to Other View`

```lua
npp:DoOpen("myfile.txt")
npp:MenuCommand(IDM_VIEW_GOTO_ANOTHER_VIEW)
```
