### ISSUE TITLE
Used defined languages

### ISSUE THREAD

**Issue by eladeyal-intel** [dail8859/LuaScript#65]
How can I apply user defined languages via luascript?
How can I see the list of configured user defined languages?

thanks

**Comment by dail8859** [comment]
> How can I apply user defined languages via luascript?

Don't have too much time right now to dig into it but you might try something like this:

```lua
npp.BufferLangType[npp.CurrentBufferID] = L_USER
```
I think this should use the file's extension to figure out what user define language to use.

> How can I see the list of configured user defined languages?

As far as I know this is not possible. This is not a limitation of LuaScript, this is a limitation of Notepad++ not providing this functionality to plugins.

**Comment by eladeyal-intel** [comment]
@dail8859  thanks for the feedback. I have several user defined languages and I wanted to use luascript to select the correct one. So I have a menu item under Language menu (below the seperator). Is it possible to read this list of menu items and activate one using script?

**Comment by dail8859** [comment]
No not using LuaScript. PythonScript might have better luck but no clue how to do it.
