### ISSUE TITLE
AddShortcut limit

### ISSUE THREAD

**Issue by jbezos** [dail8859/LuaScript#66]
I've found AddShortcut very convenient, but unfortunately I've reached the limit (about 20) very quickly. I wonder if this limit can be increased somehow.

**Comment by dail8859** [comment]
What size would you recommend?

**Comment by jbezos** [comment]
Well, who knows how many functions I'll write, but there is an obvious
limitation: keyboards have a limited number of keys (and hands a limited
number of fingers). I'm assigning all my functions to ctrl+shift (for
example, ctrl+shift+O for a toc of a LaTeX document). There are 26
letters + 10 digits + the numeric keypad + F keys, etc. So, 40-45 seems a
reasonable size.

**Comment by dail8859** [comment]
The shortcuts dont need to be assigned to a keyboard combination so in theory there is no limitation. But increasing the limit is not hard...just wanted a rough idea.

**Comment by jbezos** [comment]
Yes, I know, but I use the keyboard for almost everything, so many functions are assigned to a combination. Thank you very much. I discovered Notepad++ recently (I was using Emacs), and with your extension I can do all I need.

**Comment by dail8859** [comment]
I've increased the limit to 100 shortcuts. I don't have any plans to create a new release soon, however you can go ahead and download one of the builds from appveyor:

- [32 bit download](https://ci.appveyor.com/project/dail8859/luascript/build/job/0508iljoidqg9ir2/artifacts)
- [64 bit download](https://ci.appveyor.com/project/dail8859/luascript/build/job/vvliob9ffi9hbqpg/artifacts) 

Download one of the DLLs depending on which one you have installed and just copy over your existing plugin. *Note* that if you are using the 64 bit version your current DLL file will be named `LuaScript_64.dll` but the new 64 bit version from appveyor is just called `LuaScript.dll` so just delete your old DLL file and drop this one in.

**Comment by pidgeon777** [comment]
Does the latest [v0.10.1](https://github.com/dail8859/LuaScript/releases/tag/v0.10.1) release include the capability to allow 100 shortcuts as described above?

**Comment by dail8859** [comment]
@pidgeon777 Yes it has been included since v0.9
