### ISSUE TITLE
Wrong shortcut

### ISSUE THREAD

**Issue by jbezos** [dail8859/LuaScript#67]
Consider the following minimal `startup.lua`:

    for c = 65, 90 do
      npp.AddShortcut("Function" .. (c-64), "Ctrl+Shift+" .. string.char(c),
       function() end)
    end

The shortcut for the 16th element is wrong (R instead of P).

**Comment by jbezos** [comment]
I'll investigate a bit further to see if there is some incompatibility
with other plug-ins or a corrupted file.

**Comment by jbezos** [comment]
After a clean reinstall everything is OK, so clearly there was a corrupted file. Thank you and sorry for the noise.

**Comment by dail8859** [comment]
No problem at all. Glad it is working for you now.
