### ISSUE TITLE
Evaluation: Add LuaScript to nppPluginList

### ISSUE THREAD

**Issue by MetaChuh** [dail8859/LuaScript#68]
hi @dail8859

as LuaScript manual installation has been requested a few times, and it is a much liked plugin, would there be a possibility to add your releases to nppPluginList, or is there anything that could speak against a large scale distribution via plugins admin ?

many thanks and best regards.

**Comment by dail8859** [comment]
It is already in the plugin list:

https://github.com/notepad-plus-plus/nppPluginList/blob/master/src/pl.x64.json#L266-L275

**Comment by MetaChuh** [comment]
thanks and im soooo sorry.

i didn't check at the repo, but at a portable notepad++ 7.6.6 test instance, by searching for lua in plugins admin.

my problem was that specific test instance already had luascript installed and i didn't cross-check the already installed plugins ... and as it has been already installed there, it also means that >>> **i** <<< installed it there, so i should definitively know. 😳

greetings
