### ISSUE TITLE
Request: Guide on how to install the plugin.

### ISSUE THREAD

**Issue by SalviaSage** [dail8859/LuaScript#69]
Hi. I am a supporter of this plugin for Notepad++.

However, I was disappointed when this plugin did not work when I
copied its folder into the Notepad++\plugins directory.

Some of the other plugins work when you do that, which is of course
the default way to install the plugin.

Or, perhaps this plugin no longer works as of version 7.6.6
Can you please confirm that this plugin works and or perhaps place a readme into
the plugin so we know how to install it?

Thanks.

**Comment by SalviaSage** [comment]
Oh, the plugin works.
I just renamed the folder from LuaScript_v0.8 to LuaScript and it worked.

So, I would like to ask you to re-organize the .zip file by putting the LuaScript.dll
into a folder named LuaScript. This will facilitate an easy manual installation of the plugin.

Also, the plugin manager method is working fine, I just tested it.

See you.

**Comment by dail8859** [comment]
I'm not worried about reorganizing the zip file as I am more concerned with it being compatible with Notepad++'s built in Plugin Admin (which it is currently).

That being said, rewording the README is needed to clarify how to manually install it with Notepad++'s new plugin folder structure.
