### ISSUE TITLE
Minor suggestions

### ISSUE THREAD

**Issue by xylographe** [dail8859/LuaScript#73]
Hello Justin,

After updating toolset to v141 (commit bfc34d7aef898af4f6da1005670b1b58fcc82c66), you could update `LuaScript.sln`:
 `# Visual Studio 14` ==> `# Visual Studio 15` (as VS 2015 doesn't support toolset v141).

In `src\lua\src\luaconf.h`, the `LUA_[C]PATH_DEFAULT` could have a more useful (in the context of LuaScript) value. For example:
```C
#define LUA_LSDIR   "!\\plugins\\LuaScript\\"
#define LUA_CDIR1   LUA_LSDIR"lib\\"
#define LUA_LDIR1   LUA_CDIR1"lua\\"
#define LUA_CDIR2   LUA_LSDIR
#define LUA_LDIR2   LUA_CDIR2"lua\\"
#define LUA_PATH_DEFAULT  \
    LUA_LDIR1"?.lua;"  LUA_LDIR1"?\\init.lua;" \
    LUA_LDIR2"?.lua;"  LUA_LDIR2"?\\init.lua;" \
    LUA_CDIR1"?.lua;"  LUA_CDIR1"?\\init.lua;" \
    LUA_CDIR2"?.lua;"  LUA_CDIR2"?\\init.lua;" \
    ".\\?.lua;"  ".\\?\\init.lua"
#define LUA_CPATH_DEFAULT \
    LUA_CDIR1"?.dll;"  LUA_CDIR1"?\\loadall.dll;" \
    LUA_CDIR2"?.dll;"  LUA_CDIR2"?\\loadall.dll;" \
    ".\\?.dll;"  ".\\?\\loadall.dll"
```
Meaning, preferred DLL location is subdir — ‘lib’ or, perhaps, ‘Modules’ (like PowerShell) — below `<NPP>\plugins\LuaScript`. Alternative DLL location is LuaScript plugin directory itself. While Lua modules are preferably placed in a `lua` subdir.
Note, that the VDIR (versioned directory) doesn't make sense in the LuaScript context, because DLLs have to be rebuild if the LuaScript included lua `LUA_RELEASE` changes (e.g. from 5.3.4 to 5.3.5).

**Comment by dail8859** [comment]
Thanks for these suggestions!

Is just changing `# Visual Studio 15` enough? I didn't know if other setting would need changed as well (for example `VisualStudioVersion`)

**Comment by xylographe** [comment]
Yes, the `# Visual Studio 15` tells VS blend that it should open this solution in VS 2017 (e.g. when started with `Invoke-Item LuaScript.sln`). The `Format Version` did not change (12.0 for 2015/2017), and the `VisualStudioVersion` is maintained by VS itself.

**Comment by xylographe** [comment]
I gave Visual Studio 2017 ‘free rein’, which resulted in
```
# Visual Studio 15
VisualStudioVersion = 15.0.28307.645
```

**Comment by dail8859** [comment]
Awesome! Thanks for all the info!

Been kinda busy lately so will try to get some of theses updates put in "soon" :)

**Comment by dail8859** [comment]
> the LUA_[C]PATH_DEFAULT could have a more useful

Excellent suggestion. One of the first things I do in my startup.lua file is modify the paths manually :) And as you said the current defaults do not make sense for the way LuaScript is used.

I think I actually prefer restricting it a bit more (based off of what you posted originally).

```c
#define LUA_LSDIR   "!\\plugins\\LuaScript\\"
#define LUA_CDIR1   LUA_LSDIR"lib\\"
#define LUA_CDIR2   LUA_LSDIR
#define LUA_PATH_DEFAULT  \
    LUA_CDIR1"?.lua;"  LUA_CDIR1"?\\init.lua;" \
    LUA_CDIR2"?.lua;"  LUA_CDIR2"?\\init.lua;" \
    ".\\?.lua;"  ".\\?\\init.lua"
#define LUA_CPATH_DEFAULT \
    LUA_CDIR1"?.dll;"  LUA_CDIR1"?\\loadall.dll;" \
    LUA_CDIR2"?.dll;"  LUA_CDIR2"?\\loadall.dll;" \
    ".\\?.dll;"  ".\\?\\loadall.dll"
```

For example running `require "pickle"` will output:

```
Console:1: module 'pickle' not found:
	no field package.preload['pickle']
	no file 'C:\Program Files (x86)\Notepad++\plugins\LuaScript\lib\pickle.lua'
	no file 'C:\Program Files (x86)\Notepad++\plugins\LuaScript\lib\pickle\init.lua'
	no file 'C:\Program Files (x86)\Notepad++\plugins\LuaScript\pickle.lua'
	no file 'C:\Program Files (x86)\Notepad++\plugins\LuaScript\pickle\init.lua'
	no file '.\pickle.lua'
	no file '.\pickle\init.lua'
	no file 'C:\Program Files (x86)\Notepad++\plugins\LuaScript\lib\pickle.dll'
	no file 'C:\Program Files (x86)\Notepad++\plugins\LuaScript\lib\pickle\loadall.dll'
	no file 'C:\Program Files (x86)\Notepad++\plugins\LuaScript\pickle.dll'
	no file 'C:\Program Files (x86)\Notepad++\plugins\LuaScript\pickle\loadall.dll'
	no file '.\pickle.dll'
	no file '.\pickle\loadall.dll'
```

Unless there is some reason I am missing to support `lib`, `lua`, and `lib\lua`?

Since the `path` and `cpath` are configurable at run time, I'm not too worried about handling *all* cases someone might want to use it, but at least want something that is reasonable and sane.

**Comment by xylographe** [comment]
From all I've read about lua so far, I've come to the understanding that it is customary to keep the binary (i.e. assembly) parts and the lua scripted parts of a module separate. In the case of LuaSocket, for example, the directory hierarchy becomes:
```
<LIB>
    socket
        core.dll
    mime
        core.dll
    lua
        socket
            ftp.lua
            http.lua
            smtp.lua
            <etc>
        ltn12.lua
        mime.lua
        socket.lua
```
Where `<LIB>` could be `<NPP>\plugins\LuaScript`, `<NPP>\plugins\LuaScript\lib`, `<NPP>\plugins\LuaScript\Modules`, or whatever location you prefer. The only reason I suggested to use a subdir below `<NPP>\plugins\LuaScript` is to keep the manually user-installed modules separate from the ‘factory-installed’ LuaScript DLL(s).

Note that without the `lua` subdir `core.dll`, `ftp.lua`, `http.lua`, etc. would all be located in the same `socket` directory. Another reason for keeping these components separate is, presumably, that assemblies are platform dependant, while lua scripts are platform independant (cmp. `/usr/lib` vs `/usr/share` under Unix/Linux).

Hence, if you are looking to restrict, I think, I would rather go the other way:
```
#define LUA_LSDIR   "!\\plugins\\LuaScript\\"
#define LUA_CDIR    LUA_LSDIR"lib\\"
#define LUA_LDIR    LUA_CDIR"lua\\"
#define LUA_PATH_DEFAULT  \
    LUA_LDIR"?.lua;"  LUA_LDIR"?\\init.lua;" \
    LUA_CDIR"?.lua;"  LUA_CDIR"?\\init.lua;" \
    ".\\?.lua;"  ".\\?\\init.lua"
#define LUA_CPATH_DEFAULT \
    LUA_CDIR"?.dll;"  LUA_CDIR"?\\loadall.dll;" \
    ".\\?.dll;"  ".\\?\\loadall.dll"
```
`lib\lua\` preferred for lua components, with `lib\` as an alternative (fallback).
And, `lib\` mandatory (unless overridden in `startup.lua`) for assembly components.

Perhaps, you might even drop all four `.\\*` entries. I think (could be completely wrong, though), the ‘current directory’ might be rather unpredictable in this context (?).

**Comment by xylographe** [comment]
Addendum: One more possibility,
```
LDIR => <LSDIR>\Modules
CDIR => <LDIR>\lib
```
Perhaps, closer to the way things are organised under Windows?

**Comment by dail8859** [comment]
> I've come to the understanding that it is customary

Good point. I was curious if there was standard/customary way of packaging lua modules so if that is the case then I'm fine with supporting that. 

> The only reason I suggested to use a subdir below <NPP>\plugins\LuaScript is to keep the manually user-installed modules separate from the ‘factory-installed’ LuaScript DLL(s).

Yes I completely agree.

> Perhaps, you might even drop all four .\\* entries.

It might be beneficial to keep them. Since the `startup.lua` file does not require admin privileges (because it is in appdata (or some other user writable location)) this will allow users to also use accessible locations if they for example simply want to split up their `startup.lua` file.

> Addendum: One more possibility,

I'll play around with the paths a bit more and see what makes sense. My goal is to make it easy to use for the simple cases (a user finds a Lua file/module they want to import) and if someone wants to do something more technical or custom, then they are probably savvy enough to be able to modify the `package` paths themselves.

**Comment by dail8859** [comment]
> Perhaps, you might even drop all four .\\* entries. I think (could be completely wrong, though), the ‘current directory’ might be rather unpredictable in this context (?).

It looks like the "current directory" is where the `notepad++.exe` file is. For some reason I was assuming it was where the `startup.lua` file was. So yeah I agree this can be removed.

**Comment by dail8859** [comment]
So I think so far it looks like:

```cpp
#define LUA_LSDIR   "!\\plugins\\LuaScript\\"
#define LUA_CDIR    LUA_LSDIR"lib\\"
#define LUA_LDIR    LUA_CDIR"lua\\"
#define LUA_PATH_DEFAULT  \
    LUA_LDIR"?.lua;"  LUA_LDIR"?\\init.lua;" \
    LUA_CDIR"?.lua;"  LUA_CDIR"?\\init.lua;"
#define LUA_CPATH_DEFAULT \
    LUA_CDIR"?.dll;"  LUA_CDIR"?\\loadall.dll;"
```

Will produce:

```
Console:1: module 'pickle' not found:
	no field package.preload['pickle']
	no file 'C:\Program Files (x86)\Notepad++\plugins\LuaScript\lib\lua\pickle.lua'
	no file 'C:\Program Files (x86)\Notepad++\plugins\LuaScript\lib\lua\pickle\init.lua'
	no file 'C:\Program Files (x86)\Notepad++\plugins\LuaScript\lib\pickle.lua'
	no file 'C:\Program Files (x86)\Notepad++\plugins\LuaScript\lib\pickle\init.lua'
	no file 'C:\Program Files (x86)\Notepad++\plugins\LuaScript\lib\pickle.dll'
	no file 'C:\Program Files (x86)\Notepad++\plugins\LuaScript\lib\pickle\loadall.dll'
```

I think this seems more appropriate (it keeps everything under `lib`) and also would be sufficient for the example you posted above using luasocket.

**Comment by xylographe** [comment]
> It looks like the "current directory" is where the notepad++.exe file is.

Usually NPP will be started via a Windows shortcut file (`.lnk`), which has a “Start in” property. That “Start in” directory will become current working directory before the item (e.g. Application) in the shortcut file's “Target” property is launched. The “Start in” dir is almost always set to the location of the target item, which makes sense if the “Target type” is _not_ “Application”, but seems a bit weird otherwise, because applications can find their own directory. Obviously, applications are free to change the cwd once they've been started, apparently NPP doesn't do that.

However, I think, this might actually be an advantage: in my experience Mr(s) Average User tends to get somewhat confused when forced to make a decision without really understanding the options at offer. Additionally, one might argue that installing modules in unprotected locations like APPDATA poses a security risk, and therefore not suitable for un-savvy users.

I completely agree with the **package.path|cpath** in the previous comment: simple and adequate. And, because plug-ins are distributed in zip-archives (CMIIW) it might even be possible to include the `lib` dir with a small `README.txt` inside.

**Comment by dail8859** [comment]
> That “Start in” directory will become current working directory

Excellent point. I think allowing scripts to be loaded from the "current directory" would only add confusion.

> one might argue that installing modules in unprotected locations like APPDATA poses a security risk

I initially had this same thought and you are correct to an extent. However, if somebody wanted to do something malicious with this plugin, all they would have to do is edit the `startup.lua` (which is unprotected) and modify the `path` and `cpath` themselves and they can point it to any location.

> it might even be possible to include the lib dir with a small README.txt inside.

Agreed.

**Comment by xylographe** [comment]
> …and modify the path and cpath themselves…

Of course, absolutely right! I hadn't thought it through.
