### ISSUE TITLE
Add UniMode table

### ISSUE THREAD

**Issue by dail8859** [dail8859/LuaScript#74]
Thank you for adding BufferEncoding[].

In `startup.lua` I added,
```
UniMode = { ANSI = 0; UTF8_BOM = 1; UTF16BE_BOM = 2; UTF16LE_BOM = 3; UTF8 = 4; ASCII = 5; UTF16BE = 6; UTF16LE = 7 }
```
Perhaps, it might be convenient to make a UniMode table available through npp (e.g. `npp.UniMode.UTF8`)?

_Originally posted by @xylographe in https://github.com/dail8859/LuaScript/issues/71#issuecomment-501527619_

**Comment by dail8859** [comment]
Just went ahead and created a standalone issue else I'm sure I will totally forget about it 😄

**Comment by xylographe** [comment]
:1st_place_medal:
