### ISSUE TITLE
Line Number Control

### ISSUE THREAD

**Issue by xylographe** [dail8859/LuaScript#75]
Sometimes line numbers can be very useful, and sometimes they're not. When editing a LaTex document, for example, I prefer line numbers visible, but when writing a PoSH script I prefer the extra columns in the editor pane. With LuaScript, the `OnSwitchFile()` event, and the `BufferLangType[]` property this should be a piece of cake. Unfortunately, changing the value of `editor.MarginWidthN[0]` won't work. Or, to be more precise, it does work, but only for about a tenth of a second, before NPP decides to reset to the previous value.

Hence, it would appear, the only way to toggle line number display is to change the "Preferences > Editing > Display line number" setting. I couldn't find a `Notepad` method or property to modify this setting, but perhaps there is some `MenuCommand` I'm unaware of? Or maybe the `SendEditor()` method could solve my problem? Any hints in the right direction would be greatly appreciated.

**Comment by dail8859** [comment]
> it does work, but only for about a tenth of a second, before NPP decides to reset to the previous value.

I've found similar situations like this in the past that you have to end up fighting with Notepad++.

> perhaps there is some MenuCommand I'm unaware of?

There is:
```lua
npp:MenuCommand(IDM_VIEW_LINENUMBER)
```
But I'm not sure if this will end up doing anything different from `editor.MarginWidthN[0]` or not. Other than that I'm not aware of any "nice" ways of doing it.

The other kind of hackish way would be to use the [`StartTimer()`](https://dail8859.github.io/LuaScript/classes/Notepad.html#Notepad.StartTimer) call and use a quick one-shot timer to hide the margin soon after receiving the `OnSwitchFile()` event.

**Comment by xylographe** [comment]
Oh my, I did it again! `IDM_VIEW_LINENUMBER` is exactly what I was looking for!
But somehow I managed to overlook this macro while ‘strolling’ through `menuCmdID.h`. :-(

With `npp:MenuCommand(IDM_VIEW_LINENUMBER)` it's as simple as,
```lua
local LineNumberVisible = true

npp.AddEventHandler("OnSwitchFile", function(fileName, bufferId)
    local lang = npp.BufferLangType[bufferId]
    if lang == L_POWERSHELL or lang == L_ADA or lang == L_CS then
      if LineNumberVisible then
        npp:MenuCommand(IDM_VIEW_LINENUMBER)
        LineNumberVisible = false
      end
    elseif not LineNumberVisible then
      npp:MenuCommand(IDM_VIEW_LINENUMBER)
      LineNumberVisible = true
    end

  return false
end)
```
Fortunately "OnSwitchFile" is also triggered when NPP activates the very first tab after a re-start.

Thank you, Justin, for your help. Amazing how easy it is to automate NPP with LuaScript.

**Comment by dail8859** [comment]
Glad that did the trick!

> Amazing how easy it is to automate NPP with LuaScript.

Which is exactly the goal of LuaScript. :)
