### ISSUE TITLE
Potential plug-in update problem

### ISSUE THREAD

**Issue by xylographe** [dail8859/LuaScript#77]
Last week I updated DSpellCheck via PluginAdmin. As a result spell check was no longer possible, because the dictionaries had disappeared. Apparently, the updater renames `\plugins\DSpellCheck` first, creates a new directory, extracts the zip-ped update into the new directory, then, if there were no errors, removes (trash can) the original directory. My dictionaries were located in `\plugins\DSpellCheck\Hunspell` :)

Fortunately, DSpellCheck is flexible. I moved the dictionaries into separate directory `\plugins\DSpellCheck.Hunspell` and changed DSpellCheck's settings accordingly.

I'm aware this forum is _not_ about DSpellCheck, but there is some similarity with LuaScript, Lua modules were supposed to be kept in `\plugins\LuaScript\lib`. Obviously that would lead to the same problem: `lib` directory and everything below disappeared after LuaScript update.

To circumvent future problems, I moved my Lua modules to a separate directory, and inserted a few lines in `startup.lua`,
```lua
local function PackagePaths()
  local md = npp:GetPluginHomePath() .. [[\LuaScript.Modules\]]
  local cp = md.."?.dll;"..md.."?\\loadall.dll"
  local lp = md.."lua\\?.lua;"..md.."lua\\?\\init.lua;"..md.."?.lua;"..md.."?\\init.lua"
  return lp, cp
end
package.path, package.cpath = PackagePaths()
```

Perhaps, — better than my ad hoc solution — the updater could be enhanced: for plug-ins that need it the zip-archive could contain a special file (say `__UpdaterInfo__`), a plain, line oriented, UTF-8 encoded, text file, that will be removed before the end of the update. For example,
```
# This comment line is ignored by the updater, the empty line below too.

# Keep \plugins\LuaScript\lib directory and everything in it.
restore:directory:lib
# Specific (hypothetical) file should always be removed after update.
remove:file:lib\lua\foobar.lua
# Also remove rubbish (recursive file search)
remove:file:lib\**\*.waste
# Etc.
```

Obviously, no action is required at the moment, but I think this might be something to keep in mind.

**Comment by dail8859** [comment]
Given the recent changes to the package paths, I can see how this could cause issues.

It would be nice if the updater was able to handle this type of situation...however I doubt such changes would be easily introduced (only a small handful of plugins would need it, and the changes would be non-trivial to implement/test).

Also, when looking at it from the other end of things...one could easily argue that if you need something saved between plugin updates, you need to save it in the user's config directory (i.e. where the `startup.lua` file is saved).

So in the end it might just be best to reevaluate where the package paths are pointed to. I'll have to give it some thought.

**Comment by dail8859** [comment]
I know this issue was opened a while ago but I think once this gets resolved I'll be ready for a new release of LuaScript. The current configuration looks like:

### package.path
```
C:\Program Files\Notepad++\plugins\LuaScript\lib\lua\?.lua;
C:\Program Files\Notepad++\plugins\LuaScript\lib\lua\?\init.lua;
C:\Program Files\Notepad++\plugins\LuaScript\lib\?.lua;
C:\Program Files\Notepad++\plugins\LuaScript\lib\?\init.lua
```

### package.cpath
```
C:\Program Files\Notepad++\plugins\LuaScript\lib\?.dll;
C:\Program Files\Notepad++\plugins\LuaScript\lib\?\loadall.dll
```

So I see a few possible options:

1. Keep the current configuration as above.
    - This is the "safest/secure" option.
    - Known issue when the plugin is updated that everything in the `LuaScript` directory will get lost.
1. Put everything in the users local config directory where other settings are saved (i.e. `C:\Users\xxx\AppData\Roaming\Notepad++\plugins\Config`).
    - Not safe as it doesn't require any special permissions to update it.
    - Won't get lost between updates.
    - If the `startup.lua` file is there most users would expect you could `require` a file in the same directory.
1. Set `package.path` and `package.cpath` to be completely blank.
    - This way the user would have to decide themselves where to put files
    - Users may not even know they can configure the import paths (I know I didnt for the longest time).

---

Currently my choice is option 2. It is the most intuitive for the user, plus anyone that knows enough about Lua can change the paths themselves. Any strong objections or other thoughs?

**Comment by xylographe** [comment]
Alternative: Choose option 3 (set `package.path` and `package.cpath` to be completely blank).
When _Edit Startup Script_ is triggered for the first time, create new `startup.lua`,
```
-- Start-up script
-- Changes will take effect once Notepad++ is restarted

local function PackagePaths()
  local md = npp:GetPluginsConfigDir() .. [[\LuaScriptLibs\]]
  local cp = md.."?.dll;"..md.."?\\loadall.dll"
  local lp = md.."lua\\?.lua;"..md.."lua\\?\\init.lua;"..md.."?.lua;"..md.."?\\init.lua"
  return lp, cp
end
package.path, package.cpath = PackagePaths()
```
This will make the user aware that there is a choice.

In any case, the modules must be placed in a subdir of `\plugins\Config`, not in `\plugins\Config` itself.

**Comment by xylographe** [comment]
> Having that block of Lua at the top of everyone's start script could potentially just confuse users.

I fear, there is more truth to that than I would like to admit. :)
