### ISSUE TITLE
Colors in console aren't displayed correctly

### ISSUE THREAD

**Issue by ClaudiaFrank** [dail8859/LuaScript#8]
A [picture](http://imgur.com/l27DI2I) says more than words.
I would expect that console.StyleFore[STYLE_DEFAULT] = 0x2B91AF set the
color to this blue(ish) one.

Btw. I tried to drag this picture into here but it does always return an error.
Do you know if there is an issue with different formats, sizes etc...?

**Comment by dail8859** [comment]
Instead of `0x2B91AF` swap the first and last bytes and try `0xAF912B`

This is due to how Scintilla handles colors internally. The PythonScript does magic behind the scenes to hide this fact from the user.

**Comment by dail8859** [comment]
If you are more familiar with the other format you can do something like defining a helper function:

```lua
function RGB(color)
	return ((color & 0xff) << 16) | (color & 0xff00) | (color >> 16)
end

console.StyleFore[0] = RGB(0x2B91AF)
```

**Comment by ClaudiaFrank** [comment]
Super :-), never thought about it and as I use 1E1E1E for background I was confused why this is correct. Well , now I know why - Thank you.
