### ISSUE TITLE
editor.CurrentPos(x) doesn't work

### ISSUE THREAD

**Issue by manake** [dail8859/LuaScript#82]
The following code:

```
function func1(ch)
    editor.CurrentPos(editor.CurrentPos - 1)
end

npp.AddEventHandler("OnChar", func1)
```

doesn't move the caret to `-1` position and instead this is shown in the console:

```
File:10: attempt to call a number value (field 'CurrentPos')
stack traceback:
	File:10: in function 'func1'
```

I tried both numeric  and string values in that place (like `10` and `"10"`) but both don't work.

Should this be done somehow differently?

**Comment by xylographe** [comment]
Perhaps, `CharLeft`?
```
editor.CharLeft()
```
Or, `PositionBefore`?
```
editor.CurrentPos = editor.PositionBefore(editor.CurrentPos)
```

**Comment by dail8859** [comment]
@xylographe's suggestion is correct.

The `CurrentPos` is an integer that needs set (as the example above) and not called like a function.

**Comment by manake** [comment]
Thanks!
