### ISSUE TITLE
Loading libraries

### ISSUE THREAD

**Issue by manake** [dail8859/LuaScript#84]
Is there a way to load external libraries like https://github.com/rxi/json.lua?

**Comment by dail8859** [comment]
Yes. If you open the LuaScript console and execute

```lua
require "json"
```

It will print an error message and show you all the locations it is searching for the `json` module. The search locations can also be modified. You can read about more details in the [Lua Reference Manual](https://www.lua.org/manual/5.3/manual.html#6.3)

**Comment by manake** [comment]
Thanks!
