### ISSUE TITLE
NP++ Dedicated GPU memory spiking because of this plugin

### ISSUE THREAD

**Issue by teebu** [dail8859/LuaScript#86]
Talking about this here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8352

![image](https://user-images.githubusercontent.com/5531844/83954453-2c995700-a7fe-11ea-8559-1f3e748517a9.png)

**Comment by dail8859** [comment]
What do you have in your startup script?

**Comment by teebu** [comment]
```
-- Startup script
-- Changes will take effect once Notepad++ is restarted

editor1.Technology = SC_TECHNOLOGY_DIRECTWRITE
editor2.Technology = SC_TECHNOLOGY_DIRECTWRITE
```

**Comment by dail8859** [comment]
Have you tried removing those? 

Is there a simple way to reproduce this issue?

**Comment by teebu** [comment]
Commenting out those calls seem to resolve the issue.

**Comment by dail8859** [comment]
Then it isnt a problem with this plugin. All that does is set a flag on the two Scintilla instances within Notepad++. Your best option would be to open an issue with the Scintilla project.

**Comment by teebu** [comment]
Thanks. I set this like 5 years ago, and forgot about it. I think i was trying to make the fonts render better.

**Comment by dail8859** [comment]
Most likely the only reason someone would use this flag is to support ligatures (e.g. Fira Code font, etc)

**Comment by teebu** [comment]
There must be a memory leak in the way the implement it. If i load really big files, the value keeps going up and never releases.

**Comment by dail8859** [comment]
Again your best option is to report this to the Scintilla project as I have no clue how it actually implements the text rendering.
