### ISSUE TITLE
npp Other View

### ISSUE THREAD

**Issue by sakkamade** [dail8859/LuaScript#87]
Hello. Thank you for great plugin for `npp`.

I'm having one problem however, it is regarding `npp`'s `Other Veiw`.
Some scripts doesn't seem to work there unless I will manually `Execute Current File` 
whereas it's opened within aforementioned `Other Veiw`.

As example, I faced such problem with:
```
editor:MarkerDefine(24, SC_MARK_VERTICALBOOKMARK)

editor.ViewWS = SCWS_VISIBLEONLYININDENT
```

While following lines would work therein  flawlessly:
```
npp.AddShortcut("Copy The Line", "Ctrl+C", function()
    editor:CopyAllowLine()
end)
```
Being me using `Other View` so oftentimes as using `npp`, it appears to be rather inconvenient.

**Comment by dail8859** [comment]
I'm not sure I understand the problem exactly. The `editor` always references the current view, `editor1` always references the first view, and `editor2` references the 2nd (other) view.

If the goal is to change the marker and whitespace view on both views, you would need to manually set that on both:

```lua
editor1:MarkerDefine(24, SC_MARK_VERTICALBOOKMARK)
editor1.ViewWS = SCWS_VISIBLEONLYININDENT

editor2:MarkerDefine(24, SC_MARK_VERTICALBOOKMARK)
editor2.ViewWS = SCWS_VISIBLEONLYININDENT
```

**Comment by sakkamade** [comment]
Wah, if only I knew that...

Yes, certainly, there's no problem whatsoever.
Greatly appreciate your help.

Closing it, thank you kindly.

**Comment by dail8859** [comment]
The first few paragraphs of this part of the documentation describe them.

https://dail8859.github.io/LuaScript/classes/Editor.html
