### ISSUE TITLE
Introduce new StyleID for lua error messages

### ISSUE THREAD

**Issue by ClaudiaFrank** [dail8859/LuaScript#9]
Having a different StyleID for lua error message in the console would help to see
those lines easier and in addition having something like console.writeError which uses this
style may be helpful as well.

**Comment by dail8859** [comment]
You'll be able to log error messages with `npp.writeError(...)`. Lua error messages will also show up in red. If you want to modify the style ID for error messages you'll be able to use `console.StyleFore[39]`

**Comment by ClaudiaFrank** [comment]
Thank you for the quick commit/solution
