### ISSUE TITLE
Autocomplete crashes 64-bit N++ since 8.3

### ISSUE THREAD

**Issue by rdipardo** [dail8859/LuaScript#92]
Typing a `.` into the LuaScript console will crash 64-bit versions of N++ 8.3.1 (and 8.3).
It's caused by the autocomplete function instantiating a `Sci_TextToFind` struct with `Sci_PositionCR` fields typed as `long`:

https://github.com/dail8859/LuaScript/blob/066aeb615c08581898e124f216396f3d8aa8c1c8/src/LuaConsole.cpp#L113-L130

x64 builds of N++ now return 64-bit character range fields from all APIs that receive a pointer to a `Sci_TextToFind` or `Sci_TextRange` struct. Calling `SCI_FINDTEXT` in this context ends with a fatal exception:

![debug_crash](https://user-images.githubusercontent.com/59004801/154753869-4cfdfcee-96d2-4944-af5b-ff0f3d5e8054.png)

To reproduce:

1. Install 64-bit LuaSsript (0.11) and click "Show Console"
2. Begin typing `npp` at the prompt

![console](https://user-images.githubusercontent.com/59004801/154753909-ef537469-35ac-4b80-96f3-d0180e558b3f.png)

3. Try to type `.`
4. The editor crashes 

~~~
Notepad++ v8.3.1   (64-bit)
Build time : Feb 13 2022 - 15:41:12
Path : C:\Users\Rob\git\bin\npp_8.3.1\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 2009
OS Build : 22000.527
Current ANSI codepage : 65001
Plugins : LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll 
~~~

**Comment by dail8859** [comment]
Thanks for the report.

**Comment by ramonikus** [comment]
Hi. Not sure if it'll be known at this point, but I'm also getting a crash as soon as I press Enter key or the "Run" button (Windows 10 Pro 64-bit, N++ 8.3.2 Portable by PortableApps.com).
