### ISSUE TITLE
Not enabled for 8.3.3

### ISSUE THREAD

**Issue by donk7413** [dail8859/LuaScript#93]
I can't use the plugin since N++ 8.3.3. It's disabled.

**Comment by dail8859** [comment]
Notepad++ broke their plugin compatibility and required nearly all plugins to be recompiled. I don't have an ETA when LuaScript will be fixed unless someone creates a PR.

Related to: #92

**Comment by cmagnush** [comment]
Just create a draft pull request. Seems to work, though I haven't tested it much (and not at all with files > 2 GB). I'm new to working with Github, so let me know if I should do things differently.

**Comment by cmagnush** [comment]
Did some quick testing on a big file, and it is not working correctly. I suspect something needs to be done about IFaceTable...

**Comment by cmagnush** [comment]
Found the problem; I had somehow missed to remove a cast... I updated the pull request (with a bunch of additional fixes), and now it should work with big files.
